.TH "SINI" "1" "01 Jan 1970 (v9999)" "bofc.pl"
.SH NAME
.PP
.B sini
- shell ini - manipulate ini files from command line or shell scripts.
.SH SYNOPSIS
.PP
.BR sini\  [\  -h\  |\  -v\  ]
.br
.BR sini\  [ get ]
.RI [< file >]\ [< section >]\ < key >
.br
.BR sini\ set
.RI [< file >]\ [< section >]\ < key >\ < value >
.PP
Environment variables:
.br
.RS
.BI SINI_FILE= file
.RE
.SH DESCRIPTION
.SS COMMANDS
.TP
.B get
Retrieves value from
.I file
for
.I section key
pair.
.B get
argument can be omited, if that is the case,
.BR sini (1)
behaves just like if
.B get
was passed.
.I section
can be ommited, in which case value for
.I key
that is not in any section will be retrieved.
If
.I key
is found then value is printed on stdout.
.TP
.B set
Write new or update existing
.I section key
pair with
.I value
in
.IR file .
.B set
works in non destructive way, so all comments and whitespaces will be preserved.
When
.I section key
pair already exists in
.I file
it will be updated.
If
.I key
does not exist but
.I section
does,
.I key
will be created at the end of existing
.IR section .
If
.I section
does not exist,
.BR sini (1)
will create
.I section
at the end of file, and after that
.I key
and
.I value
will be added to that section.
If
.B set
reads data from
.BR stdin ,
modified ini will be printed to
.BR stdout .
.BR sini (1)
does not work with malformed input, if it finds anything it does not like,
it will abort and original
.I file
will not be modified.
.SS OPTIONS
.TP
.I file
Path to a ini file.
When
.B SINI_FILE
environment variable is set, this parameters should be omited.
When
.I file
is
.RB ' - '
(dash) character, ini structure is read from
.B stdin
instead.
.TP
.I section
Ini section to work on.
.I section
is optional and can be ommited.
If empty string is provided
.BR sini (1)
acts like if
.I section
was not set at all.
Every
.I key
that exists before any
.I section
declaration is considered to be in no-section.
.TP
.I key
Ini
.I key
to work on.
.TP
.I value
Valid only for
.B set
command.
This value will be assigned to specified
.IR key .
.I value
cannot contain new line characters, since
.BR sini (1)
does not support multiline values.
.SH "INI SPECIFICATION"
.PP
Since ini does not have any official specification, here are some
assumptions made by
.BR sini (1).
.TP
multiline
No multiline support, one declaration per line. Of course comments can be
multiline.
.TP
sections,
Section starts with '[' and ends with ']' on the same line, leading spaces
are ignored, you can use any printable characters in section name,
including spaces.
Section is optional, all keys before any section definition are considered
to be in "no-section" zone and can be retrieved by not passing
.I section
or by passing empty string.
.TP
key
In "key", all leading and trailing spaces around key are ignored, but
spaces in keys are allowed, so
.br
.B "    '  space key='"
.br
.B "    'space key ='"
.br
.B "    'space key   ='"
.br
are all considered to be the very same key - "space key", but
.br
.B "    '  space  key ='
.br
is different - there are 2 spaces between space and key.
Keys without value are allowed.
.TP
value
In "value", leading spaces after "=" are ignored, but trailing spaces are
kept. All characters are allowed
.TP
comments
Comments starts with ';', leading spaces are ignored in comments, so " ;
comment" is valid, no inline comments possible "key = value ; comment" is
not valid, and value for the "key" will be "value ; comment", literaly.
.SH "BUG REPORTING"
.PP
Please, report all bugs to "Michał Łyszczek <michal.lyszczek@bofc.pl>"
